# This is a basic workflow to help you get started with Actions

name: DEPLOY TESTX TO AWS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: executing remote ssh commands using password
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_stop: true
          script: |
            echo "${{ github.event.head_commit.message }}" >> "test.txt"
            echo "${{ github.event.head_commit.body }}" >> "test.txt"
            echo "test" >> test.txt
            
#       - name: executing remote ssh commands using password
#         if: contains(github.event.head_commit.message, '#hotfix') == false
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_SSH_HOST }}
#           username: ${{ secrets.SERVER_SSH_USERNAME }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script_stop: true
#           script: |
#             whoami
#             ls -al
#             echo "run~ plz run~" >> "test.txt" 
            
            
            
#       - name: executing remote ssh commands using password
#         if: contains(github.event.head_commit.body, '#hotfix') == false
# #         if: contains(github.event.head_commit.message, '#hotfix') == false
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_SSH_HOST }}
#           username: ${{ secrets.SERVER_SSH_USERNAME }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script_stop: true
#           script: |
#             whoami
#             ls -al
#             echo "run~ plz run~" >> "test.txt"
